/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe detail by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeDetail"];
                    };
                };
                /** @description Invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Instruction: {
            stepNumber: number;
            instruction: string;
        };
        RecipeDetail: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uri */
            imageUrl?: string | null;
            description: string;
            servings: number;
            preptime?: number;
            cookTime: number;
            /** @enum {integer} */
            effortLevel: 1 | 2 | 3 | 4 | 5;
            ingredients: string[];
            instructions: components["schemas"]["Instruction"][];
            tags: string[];
        } | {
            prepTime?: unknown;
        } | {
            cookTimeTime?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
